[package]
name = "snmp_trapserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rdkafka = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snmp-parser = "0.7"
crossbeam-channel = "0.5"